name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write  # Needed to create releases

env:
  APP: web-app
  PACKAGE: web-app.tar.gz

jobs:
  goreleaser:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Build Application
        run: |
          go build -o ${{env.APP}} ./src/web-app
          tar -czvf ${{env.PACKAGE}} ${{env.APP}}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{env.PACKAGE}}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Release to remote repository
        uses: peter-evans/repository-dispatch@v3
        env:
          TARGET: sibuthomasmathew/ci-tests
        with:
          token: ${{ secrets.CI }}
          repository: ${{ env.TARGET }}
          event-type: release-triggered
          client-payload: '{
              "version": "${{  github.ref_name }}"
            }'
