name: Trigger container build on Release

on:
  release:
    types: [published]  # Triggers when a new release is published

env:
  TARGET: https://github.com/sibuthomasmathew/ci-tests
    
jobs:
  trigger-container-build:
    runs-on: ubuntu-latest
    steps:
      - name: Send Dispatch Event to Repo 2
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.CI }}" \
            ${{ env.TARGET }}/dispatches \
            -d '{"event_type": "release-triggered", "client_payload": { "version": "${{ github.event.release.tag_name }}" }}'
